###

POST {{host}}/api/v1/device/test0/properties/_query_each_one
Content-Type: application/json
X-Access-Token: {{token}}

{
"where": "timestamp > 1591697937738"
}

###
POST {{host}}/api/v1/device/test0/agg/count/temperature/_query
Content-Type: application/json
X-Access-Token: {{token}}

{

}